import hashlib,json,math
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
T=["SPY","QQQ"]; COSTS=(0.5,1.0,2.0); PC=1.0; WINDOWS={"2010":"2010-01-01","2015":"2015-01-01","2020":"2020-01-01"}
def met(r):
 r=pd.Series(r,dtype=float).dropna(); e=(1+r).cumprod(); c=float(e.iloc[-1]**(252/len(r))-1); v=float(r.std(ddof=0)*math.sqrt(252)); return {"cagr":c,"sharpe":float(r.mean()*252/v) if v else None,"maxdd":float((e/e.cummax()-1).min())}
def ev(z,cost):
 net=z.gross-z.turn*cost/10000; a,s=met(net),met(z.spy); fs=[]
 for i,ix in enumerate(np.array_split(np.arange(len(z)),5),1):
  q=z.iloc[ix]; n=q.gross-q.turn*cost/10000; fs.append({"fold":i,"cash_excess":met(n)["cagr"],"spy_excess":met(n)["cagr"]-met(q.spy)["cagr"]})
 return {"days":len(z),"candidate":a,"spy":s,"excess_cash":a["cagr"],"excess_spy_opportunity":a["cagr"]-s["cagr"],"positive_cash_folds":sum(x["cash_excess"]>0 for x in fs),"positive_spy_folds":sum(x["spy_excess"]>0 for x in fs),"corr_spy":float(net.corr(z.spy)),"turnover_per_day":float(z.turn.mean()),"folds":fs}
raw=yf.download(T,start="2007-01-01",end="2026-09-03",auto_adjust=True,progress=False,group_by="column",threads=False); o=raw["Open"][T]; c=raw["Close"][T]; panel=pd.concat({"open":o,"close":c},axis=1).dropna(); o=panel["open"]; c=panel["close"]; overnight=(o/c.shift(1)-1).mean(axis=1); spy=c.SPY.pct_change(); z=pd.DataFrame({"gross":overnight,"spy":spy,"turn":2.0}).dropna(); tests={str(cb):{k:ev(z.loc[pd.Timestamp(st):],cb) for k,st in WINDOWS.items()} for cb in COSTS}; p=tests[str(PC)]["2015"]; s2=tests["2.0"]["2015"]; decision="P194_OVERNIGHT_ONLY_SURVIVOR" if p["excess_cash"]>0 and p["positive_cash_folds"]>=3 and p["candidate"]["sharpe"]>=p["spy"]["sharpe"] and p["candidate"]["maxdd"]>=-0.20 and s2["excess_cash"]>0 else "P194_OVERNIGHT_ONLY_REJECT"; out={"schema":"research.p194_overnight_only_r1","parent":"P194","hypothesis":"The SPY/QQQ overnight return segment creates a durable long-only alpha sleeve after explicit daily round-trip costs.","contract":{"assets":T,"strategy":"equal-weight SPY/QQQ from prior close to next open, cash intraday","turnover_model":"2 portfolio-notional one-way units per trading day","cost_bps_one_way":COSTS,"primary_cost_bps":PC,"matched":"cash zero return for partial-day alpha sleeve","opportunity_control":"SPY buy-and-hold; candidate Sharpe must exceed SPY at primary gate","windows":WINDOWS,"folds":5,"gate":"2015+ at 1 bp one-way: positive CAGR vs cash, >=3/5 positive cash folds, Sharpe >= SPY, max DD >=-20%, still positive CAGR at 2 bps","no_asset_cost_or_chronology_search":True},"source":{"provider":"Yahoo Finance adjusted OHLC via yfinance; research-only","rows":len(panel),"last":str(panel.index[-1]),"panel_sha256":hashlib.sha256(panel.to_csv().encode()).hexdigest()},"tests":tests,"decision":decision,"boundaries":{"portfolio_ranking":False,"product_runtime":False,"broker":False,"live_trading":False}}; Path('artifacts').mkdir(exist_ok=True); Path('artifacts/p194_overnight_only_r1.json').write_text(json.dumps(out,sort_keys=True,indent=2)); print(json.dumps(out,sort_keys=True))