import hashlib,json,math
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
A=["XLB","XLE","XLF","XLI","XLK","XLP","XLU","XLV","XLY"]; ALL=A+["SPY"]; COSTS=(10,25,50); PC=25; WINDOWS={"2005":"2005-01-01","2010":"2010-01-01","2015":"2015-01-01","2020":"2020-01-01"}
def met(r):
 r=pd.Series(r,dtype=float).dropna(); e=(1+r).cumprod(); c=float(e.iloc[-1]**(12/len(r))-1); v=float(r.std(ddof=0)*math.sqrt(12)); return {"cagr":c,"sharpe":float(r.mean()*12/v) if v else None,"maxdd":float((e/e.cummax()-1).min())}
def ev(z,c):
 net=z.rebal-z.turn*c/10000; a,b,s=met(net),met(z.buyhold),met(z.spy); fs=[]
 for i,ix in enumerate(np.array_split(np.arange(len(z)),5),1):
  q=z.iloc[ix]; n=q.rebal-q.turn*c/10000; fs.append({"fold":i,"matched_excess":met(n)["cagr"]-met(q.buyhold)["cagr"],"spy_excess":met(n)["cagr"]-met(q.spy)["cagr"]})
 return {"months":len(z),"candidate":a,"buyhold_identical_basket":b,"spy":s,"excess_matched":a["cagr"]-b["cagr"],"excess_spy_opportunity":a["cagr"]-s["cagr"],"positive_matched_folds":sum(x["matched_excess"]>0 for x in fs),"mean_turnover":float(z.turn.mean()),"folds":fs}
raw=yf.download(ALL,start="1999-01-01",end="2026-09-03",auto_adjust=True,progress=False,group_by="column",threads=False); c=raw["Close"][ALL] if isinstance(raw.columns,pd.MultiIndex) else raw[ALL]; c=c.dropna(how="any"); m=c.resample("ME").last(); r=m.pct_change().dropna(); w0=pd.Series(1/len(A),index=A); bh=w0.copy(); rows=[]
for dt,row in r.iterrows():
 rebal=float((w0*row[A]).sum()); bhret=float((bh*row[A]).sum()); post=bh*(1+row[A]); bh=post/post.sum(); turn=float(np.abs(w0-(w0*(1+row[A])/(1+rebal))).sum()/2); rows.append({"date":dt,"rebal":rebal,"buyhold":bhret,"spy":float(row.SPY),"turn":turn})
z=pd.DataFrame(rows).set_index("date"); tests={str(cb):{k:ev(z.loc[pd.Timestamp(st):],cb) for k,st in WINDOWS.items()} for cb in COSTS}; p=tests[str(PC)]["2010"]; p15=tests[str(PC)]["2015"]; decision="P195_SECTOR_REBALANCE_PREMIUM_SURVIVOR" if p["excess_matched"]>0 and p15["excess_matched"]>0 and p["positive_matched_folds"]>=3 and p["candidate"]["sharpe"]>=p["buyhold_identical_basket"]["sharpe"] and tests['50']['2010']['excess_matched']>0 else "P195_SECTOR_REBALANCE_PREMIUM_REJECT"; out={"schema":"research.p195_sector_rebalance_premium_r1","parent":"P195","hypothesis":"Mechanical monthly equal-weight rebalancing across the nine legacy SPDR sectors earns a durable after-cost rebalancing premium versus buy-and-hold exposure to the identical starting basket.","contract":{"assets":A,"candidate":"rebalance to equal weight monthly after completed month","matched":"buy-and-hold same equal-weight starting basket, no subsequent rebalancing","opportunity_control":"SPY","cost_bps_one_way":COSTS,"primary_cost_bps":PC,"windows":WINDOWS,"folds":5,"gate":"2010+ at 25 bps: positive matched excess, 2015+ positive matched excess, >=3/5 positive matched folds, Sharpe >= matched, and 2010+ matched excess remains positive at 50 bps","no_asset_frequency_cost_or_chronology_search":True},"source":{"provider":"Yahoo Finance via yfinance; research-only","rows":len(c),"last":str(c.index[-1]),"panel_sha256":hashlib.sha256(c.to_csv().encode()).hexdigest()},"tests":tests,"decision":decision,"boundaries":{"portfolio_ranking":False,"product_runtime":False,"broker":False,"live_trading":False}}; Path('artifacts').mkdir(exist_ok=True); Path('artifacts/p195_sector_rebalance_premium_r1.json').write_text(json.dumps(out,sort_keys=True,indent=2)); print(json.dumps(out,sort_keys=True))