import hashlib,json,math
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
A=["XLB","XLE","XLF","XLI","XLK","XLP","XLU","XLV","XLY"]; ALL=A+["SPY"]; COSTS=(10,25,50); PC=25; WINDOWS={"2005":"2005-01-01","2010":"2010-01-01","2015":"2015-01-01","2020":"2020-01-01"}
def met(r):
 r=pd.Series(r).dropna(); e=(1+r).cumprod(); c=float(e.iloc[-1]**(12/len(r))-1); v=float(r.std(ddof=0)*math.sqrt(12)); return {"cagr":c,"sharpe":float(r.mean()*12/v) if v else None,"maxdd":float((e/e.cummax()-1).min())}
def ev(m,start,cost):
 r=m.pct_change().dropna().loc[start:]; w0=pd.Series(1/len(A),index=A); bh=w0.copy(); rows=[]
 for dt,row in r.iterrows():
  cand=float((w0*row[A]).sum()); matched=float((bh*row[A]).sum()); post=bh*(1+row[A]); bh=post/post.sum(); drift=w0*(1+row[A])/(1+cand); turn=float((w0-drift).abs().sum()/2); rows.append((dt,cand,matched,float(row.SPY),turn))
 z=pd.DataFrame(rows,columns=['date','candidate','matched','spy','turn']).set_index('date'); net=z.candidate-z.turn*cost/10000; a,b,s=met(net),met(z.matched),met(z.spy); fs=[]
 for i,ix in enumerate(np.array_split(np.arange(len(z)),5),1):
  q=z.iloc[ix]; n=q.candidate-q.turn*cost/10000; fs.append({"fold":i,"matched_excess":met(n)['cagr']-met(q.matched)['cagr']})
 return {"months":len(z),"candidate":a,"matched":b,"spy":s,"matched_excess":a['cagr']-b['cagr'],"spy_opportunity_excess":a['cagr']-s['cagr'],"positive_matched_folds":sum(x['matched_excess']>0 for x in fs),"mean_turnover":float(z.turn.mean()),"folds":fs}
raw=yf.download(ALL,start="1999-01-01",end="2026-09-03",auto_adjust=True,progress=False,group_by="column",threads=False); c=raw['Close'][ALL] if isinstance(raw.columns,pd.MultiIndex) else raw[ALL]; c=c.dropna(how='any'); m=c.resample('ME').last(); tests={str(cb):{k:ev(m,s,cb) for k,s in WINDOWS.items()} for cb in COSTS}; p=tests[str(PC)]['2010']; p15=tests[str(PC)]['2015']; decision='P199_P195_CORRECTED_BASELINE_SURVIVOR' if p['matched_excess']>0 and p15['matched_excess']>0 and p['positive_matched_folds']>=3 and tests['50']['2010']['matched_excess']>0 else 'P199_P195_CORRECTED_BASELINE_REJECT'; out={"schema":"research.p199_p195_baseline_correction_r1","parent":"P199","related_claim":"P195","hypothesis":"P195's reported rebalancing premium survives when the buy-and-hold matched basket is initialized to the same equal weights at the start of every declared evaluation window.","contract":{"assets":A,"candidate":"monthly equal-weight rebalance","matched":"equal-weight identical basket initialized independently at each evaluation-window start then buy-and-hold","opportunity":"SPY","cost_bps_one_way":COSTS,"primary_cost_bps":PC,"windows":WINDOWS,"folds":5,"gate":"unchanged P195 matched-alpha gate with corrected comparator initialization: 2010+ and 2015+ positive matched excess, >=3/5 positive matched folds from 2010, positive 2010+ matched excess at 50 bps","no_asset_frequency_cost_weight_or_chronology_search":True},"source":{"provider":"Yahoo Finance via yfinance; research-only","rows":len(c),"last":str(c.index[-1]),"panel_sha256":hashlib.sha256(c.to_csv().encode()).hexdigest()},"tests":tests,"decision":decision,"boundaries":{"portfolio_ranking":False,"product_runtime":False,"broker":False,"live_trading":False}}; Path('artifacts').mkdir(exist_ok=True); Path('artifacts/p199_p195_baseline_correction_r1.json').write_text(json.dumps(out,sort_keys=True,indent=2)); print(json.dumps(out,sort_keys=True))