from __future__ import annotations
import json
from pathlib import Path
import pandas as pd,yfinance as yf
SYMS=['SPMO','SPY','CALF','IJR']; START='2018-01-01'; END='2026-09-10'; BLOCKS={'2019_2021':('2019-01-01','2021-12-31'),'2022_2024':('2022-01-01','2024-12-31'),'2025_present':('2025-01-01','2026-09-10')}
raw=yf.download(SYMS,start=START,end=END,auto_adjust=True,progress=False,threads=False); px=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw)[SYMS].dropna().resample('ME').last(); r=px.pct_change().dropna(); x=pd.DataFrame({'spmo_excess':r.SPMO-r.SPY,'calf_excess':r.CALF-r.IJR}).dropna(); results={}
for n,(a,b) in BLOCKS.items():
 z=x.loc[(x.index>=pd.Timestamp(a))&(x.index<=pd.Timestamp(b))]; weak=z.spmo_excess<0; strong=z.spmo_excess>0
 results[n]={'months':int(len(z)),'excess_corr':float(z.spmo_excess.corr(z.calf_excess)),'spmo_mean_excess':float(z.spmo_excess.mean()),'calf_mean_excess':float(z.calf_excess.mean()),'calf_mean_when_spmo_negative':float(z.loc[weak,'calf_excess'].mean()) if weak.any() else None,'calf_positive_fraction_when_spmo_negative':float((z.loc[weak,'calf_excess']>0).mean()) if weak.any() else None,'spmo_negative_months':int(weak.sum()),'both_negative_fraction':float(((z.spmo_excess<0)&(z.calf_excess<0)).mean()),'opposite_sign_fraction':float(((z.spmo_excess*z.calf_excess)<0).mean())}
allcorr=float(x.loc[x.index>=pd.Timestamp('2019-01-01')].spmo_excess.corr(x.loc[x.index>=pd.Timestamp('2019-01-01')].calf_excess)); lowcorr=sum(v['excess_corr']<0.5 for v in results.values()); offset=sum((v['calf_mean_when_spmo_negative'] or 0)>0 for v in results.values()); decision='P294_RELATIVE_EXCESS_COMPLEMENTARITY_SUPPORTED' if lowcorr>=2 and offset>=2 else 'P294_RELATIVE_EXCESS_COMPLEMENTARITY_WEAK_OR_MIXED'
out={'schema':'research.p294_relative_complementarity_r1','parent':'P294','claim':'Explain, without tuning, whether CALF contributes diversification to the frozen SPMO+CALF pair because its matched-relative excess is sufficiently distinct and tends to remain positive when SPMO relative excess is negative.','blocks':BLOCKS,'results':results,'summary':{'2019_plus_excess_corr':allcorr,'blocks_excess_corr_below_0_5':lowcorr,'blocks_calf_mean_positive_when_spmo_negative':offset},'decision_rule':'Complementarity support requires relative-excess correlation below 0.5 in at least 2/3 fixed blocks and positive average CALF-vs-IJR excess during SPMO-vs-SPY negative months in at least 2/3 blocks. This is explanatory attribution only; failure narrows the diversification mechanism claim and does not invalidate P290/P291 combination evidence.','decision':decision,'limitations':['monthly matched-relative arithmetic return differences are an attribution representation, not portfolio PnL','same adjusted-price provider as combination evidence','scientific attribution only; no allocation/ranking/runtime/broker/live authority'],'boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/p294_relative_complementarity_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))
