from __future__ import annotations
import json
from pathlib import Path
import pandas as pd,yfinance as yf
SYMS=['SPMO','SPY','XMMO','IJH']; START='2015-01-01'; END='2026-09-10'; BLOCKS={'2017_2019':('2017-01-01','2019-12-31'),'2020_2022':('2020-01-01','2022-12-31'),'2023_present':('2023-01-01','2026-09-10')}
raw=yf.download(SYMS,start=START,end=END,auto_adjust=True,progress=False,threads=False); px=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw)[SYMS].dropna().resample('ME').last(); r=px.pct_change().dropna(); x=pd.DataFrame({'spmo_excess':r.SPMO-r.SPY,'xmmo_excess':r.XMMO-r.IJH}).dropna(); results={}
for n,(a,b) in BLOCKS.items():
 z=x.loc[(x.index>=pd.Timestamp(a))&(x.index<=pd.Timestamp(b))]; results[n]={'months':int(len(z)),'excess_corr':float(z.spmo_excess.corr(z.xmmo_excess)),'spmo_mean_excess':float(z.spmo_excess.mean()),'xmmo_mean_excess':float(z.xmmo_excess.mean()),'opposite_sign_fraction':float(((z.spmo_excess*z.xmmo_excess)<0).mean()),'both_negative_fraction':float(((z.spmo_excess<0)&(z.xmmo_excess<0)).mean())}
z=x.loc[x.index>=pd.Timestamp('2017-01-01')]; corr=float(z.spmo_excess.corr(z.xmmo_excess)); low=sum(v['excess_corr']<0.6 for v in results.values()); decision='P300_MOMENTUM_COMPLEMENTARITY_PLAUSIBLE' if corr<0.6 and low>=2 else 'P300_MOMENTUM_REDUNDANCY_HIGH'
out={'schema':'research.p300_spmo_xmmo_redundancy_r1','parent':'P300','claim':'Before combining the independently supported SPMO and XMMO momentum sleeves, test whether their matched-relative excess streams are sufficiently distinct to justify a complementarity hypothesis rather than treating two momentum funds as independent alpha sources.','blocks':BLOCKS,'results':results,'summary':{'2017_plus_excess_corr':corr,'blocks_excess_corr_below_0_6':low},'decision_rule':'Complementarity is only plausible if 2017+ matched-relative excess correlation is below 0.6 and at least 2/3 fixed blocks are below 0.6. Otherwise classify high redundancy and do not advance a combination solely because both individual sleeves pass.','decision':decision,'limitations':['relative-excess correlation is a scientific redundancy discriminator, not allocation optimization','same adjusted-price provider','scientific evidence only; no allocation/ranking/runtime/broker/live authority'],'boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/p300_spmo_xmmo_redundancy_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))
