from __future__ import annotations
import json
from pathlib import Path
import pandas as pd, yfinance as yf
SYMS=['SPMO','SPY','VBR','VB']; START='2015-01-01'; END='2026-09-10'; BLOCKS={'2017_2019':('2017-01-01','2019-12-31'),'2020_2022':('2020-01-01','2022-12-31'),'2023_present':('2023-01-01','2026-09-10')}
raw=yf.download(SYMS,start=START,end=END,auto_adjust=True,progress=False,threads=False); px=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw)[SYMS].dropna().resample('ME').last(); r=px.pct_change().dropna(); x=pd.DataFrame({'spmo_excess':r.SPMO-r.SPY,'smallvalue_excess':r.VBR-r.VB}).dropna(); results={}
for n,(a,b) in BLOCKS.items():
 z=x.loc[(x.index>=pd.Timestamp(a))&(x.index<=pd.Timestamp(b))]; results[n]={'months':int(len(z)),'excess_corr':float(z.spmo_excess.corr(z.smallvalue_excess)),'spmo_mean_excess':float(z.spmo_excess.mean()),'smallvalue_mean_excess':float(z.smallvalue_excess.mean()),'opposite_sign_fraction':float(((z.spmo_excess*z.smallvalue_excess)<0).mean()),'both_negative_fraction':float(((z.spmo_excess<0)&(z.smallvalue_excess<0)).mean())}
z=x.loc[x.index>=pd.Timestamp('2017-01-01')]; corr=float(z.spmo_excess.corr(z.smallvalue_excess)); low=sum(v['excess_corr']<0.4 for v in results.values()); decision='P301_ORTHOGONAL_COMPLEMENTARITY_PLAUSIBLE' if corr<0.4 and low>=2 else 'P301_COMPLEMENTARITY_NOT_ESTABLISHED'
out={'schema':'research.p301_spmo_smallvalue_redundancy_r1','parent':'P301','claim':'Test whether supported SPMO momentum excess and recent small-value matched excess are genuinely orthogonal enough to justify a scientific complementarity hypothesis after P300 rejected naive SPMO-XMMO combination.','representations':{'momentum':'SPMO minus SPY','small_value':'VBR minus VB'},'blocks':BLOCKS,'results':results,'summary':{'2017_plus_excess_corr':corr,'blocks_excess_corr_below_0_4':low},'decision_rule':'Orthogonal complementarity is plausible only if 2017+ matched-relative excess correlation is below 0.4 and at least 2/3 fixed blocks are below 0.4. Otherwise do not advance a combination claim.','decision':decision,'limitations':['scientific redundancy discriminator, not allocation optimization','VBR/VB transport is mixed/regime-conditional evidence and does not redefine P249','same adjusted-price provider','no parameter, weight, product, runtime, broker, or live authority'],'boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/p301_spmo_smallvalue_redundancy_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))
