from __future__ import annotations
import json
from pathlib import Path
import pandas as pd, yfinance as yf
SYMS=['CALF','IJS','IJR']; START='2017-01-01'; END='2026-09-10'; BLOCKS={'2018_2019':('2018-01-01','2019-12-31'),'2020_2022':('2020-01-01','2022-12-31'),'2023_present':('2023-01-01','2026-09-10')}
raw=yf.download(SYMS,start=START,end=END,auto_adjust=True,progress=False,threads=False); px=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw)[SYMS].dropna().resample('ME').last(); r=px.pct_change().dropna(); x=pd.DataFrame({'calf_excess':r.CALF-r.IJR,'smallvalue_excess':r.IJS-r.IJR}).dropna(); results={}
for n,(a,b) in BLOCKS.items():
 z=x.loc[(x.index>=pd.Timestamp(a))&(x.index<=pd.Timestamp(b))]; results[n]={'months':int(len(z)),'excess_corr':float(z.calf_excess.corr(z.smallvalue_excess)),'opposite_sign_fraction':float(((z.calf_excess*z.smallvalue_excess)<0).mean()),'both_negative_fraction':float(((z.calf_excess<0)&(z.smallvalue_excess<0)).mean())}
z=x.loc[x.index>=pd.Timestamp('2018-01-01')]; corr=float(z.calf_excess.corr(z.smallvalue_excess)); low=sum(v['excess_corr']<0.6 for v in results.values()); decision='P321_CALF_DISTINCT_RETURN_SOURCE_PLAUSIBLE' if corr<0.6 and low>=2 else 'P321_CALF_SMALLVALUE_REDUNDANCY_HIGH'
out={'schema':'research.p321_calf_smallvalue_redundancy_r1','parent':'P321','claim':'Adjudicate whether P319 CALF-vs-IJR conditional free-cash-flow evidence is distinct from the already-supported IJS-vs-IJR small-value source using monthly matched-relative excess correlation. No new product, weight, factor-definition, or window search.','representations':{'calf_excess':'CALF-IJR','small_value_excess':'IJS-IJR'},'blocks':BLOCKS,'results':results,'summary':{'2018_plus_excess_corr':corr,'blocks_excess_corr_below_0_6':low},'decision_rule':'Distinct return-source plausibility requires 2018+ matched-relative excess correlation below 0.6 and at least 2/3 fixed blocks below 0.6. Otherwise preserve CALF standalone passing evidence but do not treat it as orthogonal to small value.','decision':decision,'limitations':['mechanism/redundancy discriminator, not causal constituent proof','same adjusted-price provider','no allocation/ranking/product/runtime/broker/live authority'],'boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/p321_calf_smallvalue_redundancy_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))