from __future__ import annotations
import json, math
from pathlib import Path
import numpy as np, pandas as pd, yfinance as yf
SYMS=['FPX','IWB','SPY','QQQ']; START='2006-04-01'; END='2026-09-10'; COST_BPS=10
raw=yf.download(SYMS,start=START,end=END,auto_adjust=True,progress=False,threads=False); px=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw)[SYMS].dropna(); r=px.resample('ME').last().pct_change().dropna()
def net_endpoint(s):
 x=s.copy(); x.iloc[0]-=COST_BPS/10000; x.iloc[-1]-=COST_BPS/10000; return x
def stats(s):
 s=s.dropna(); w=(1+s).cumprod(); yrs=len(s)/12; sd=s.std(); return {'months':int(len(s)),'cagr':float(w.iloc[-1]**(1/yrs)-1),'sharpe':float(s.mean()/sd*math.sqrt(12)) if sd>0 else 0.0,'max_drawdown':float((w/w.cummax()-1).min())}
res={}
for name,start in {'2007_plus':'2007-01-01','2015_plus':'2015-01-01','2020_plus':'2020-01-01'}.items():
 q=r.loc[start:]; a,b,sp,nq=[stats(net_endpoint(q[c])) for c in SYMS]; res[name]={'fund':a,'iwb_matched':b,'spy':sp,'qqq_context':nq,'matched_excess_cagr':a['cagr']-b['cagr'],'spy_gap_cagr':a['cagr']-sp['cagr'],'qqq_gap_cagr':a['cagr']-nq['cagr']}
z=r.loc['2007-01-01':,['FPX','IWB']].dropna(); folds=[stats(net_endpoint(f.FPX))['cagr']-stats(net_endpoint(f.IWB))['cagr'] for f in np.array_split(z,5)]; passed=all(v['matched_excess_cagr']>0 for v in res.values()) and sum(v>0 for v in folds)>=4 and all(v['fund']['max_drawdown']>=v['iwb_matched']['max_drawdown']-0.10 for v in res.values()); decision='P349_IPO_SELECTION_FUND_CANDIDATE_SUPPORTED' if passed else 'P349_IPO_SELECTION_FUND_NOT_SUPPORTED'
out={'schema':'research.p349_ipo_selection_fund_r1','parent':'P349','claim':'Prospectively frozen event/cohort-selection investable-fund discriminator: FPX newly public company exposure versus IWB broad-US matched control, with SPY and QQQ opportunity-cost context. Buy/hold only, 10bp entry plus 10bp terminal friction, fixed 2007+/2015+/2020+ windows and five chronology folds. No IPO holding-period, fund, timing, weighting, threshold, date, or cost search.','cost_bps_each_endpoint':COST_BPS,'months_available':int(len(r)),'results':res,'chronology_fold_matched_excess_cagr':folds,'positive_folds':sum(v>0 for v in folds),'decision_rule':'Candidate support requires >=180 monthly observations, positive after-cost matched excess in every fixed window, >=4/5 positive chronology folds, and no fixed-window max drawdown more than 10pp worse than IWB. Failure rejects this exact fund formulation without parameter rescue; a pass still requires independent representation/source validation.','decision':decision,'limitations':['single investable fund implementation; any pass requires independent validation','fund owns firms after IPO rather than primary-market issuance returns','adjusted prices include fund expenses/distributions but not investor taxes','QQQ is opportunity context not matched baseline','no allocation/ranking/product/runtime/broker/live authority'],'boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/p349_ipo_selection_fund_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))