from __future__ import annotations
import json
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
OUT=Path('research/artifacts/p449_growth_tech_falsifier_r1.json'); OUT.parent.mkdir(parents=True,exist_ok=True)
FUNDS=['VUG','IWF']; WINDOWS=['2010-01-01','2016-01-01','2020-01-01']; BLOCKS=[('2010-01-01','2013-12-31'),('2014-01-01','2017-12-31'),('2018-01-01','2021-12-31'),('2022-01-01','2026-09-10')]
p=yf.download(FUNDS+['SPY','XLK'],start='2009-01-01',end='2026-09-11',auto_adjust=True,progress=False)['Close'].dropna(); r=p.pct_change(fill_method=None).dropna()
def m(s,a,b=None):
 z=r.loc[a:b,[s,'SPY','XLK']].dropna(); y=z[s].values; X=np.column_stack([np.ones(len(z)),z.SPY.values,z.XLK.values]); coef=np.linalg.lstsq(X,y,rcond=None)[0]; resid=y-X@coef; return {'days':len(z),'alpha_annual':float(coef[0]*252),'spy_beta':float(coef[1]),'xlk_beta':float(coef[2]),'residual_vol_annual':float(np.std(resid,ddof=1)*np.sqrt(252))}
res={s:{'windows':[m(s,a) for a in WINDOWS],'blocks':[m(s,a,b) for a,b in BLOCKS]} for s in FUNDS}
def ok(v):return all(x['alpha_annual']>0 for x in v['windows']) and sum(x['alpha_annual']>0 for x in v['blocks'])>=3
passed=all(ok(v) for v in res.values()); out={'schema':'research.p449_growth_tech_falsifier_r1.v1','workload_id':'P449_GROWTH_TECH_FALSIFIER_R1','parent':'US_GROWTH_FACTOR_FUND_ALPHA','claim':'P447 growth-factor alpha should remain positive after jointly controlling for broad-market and technology-sector exposure; otherwise the apparent edge is largely technology concentration rather than an independent growth factor.','contract':{'funds':FUNDS,'controls':['SPY','XLK'],'model':'daily OLS fund_return ~ intercept + SPY + XLK','fixed_windows':WINDOWS,'chronology_blocks':BLOCKS,'acceptance':'Both funds positive annualized intercept in all fixed windows and >=3/4 chronology blocks. No factor/date/product rescue.'},'results':res,'decision':'GROWTH_RESIDUAL_ALPHA_AFTER_TECH_SUPPORTED' if passed else 'GROWTH_RESIDUAL_ALPHA_AFTER_TECH_NOT_SUPPORTED','scientific_consequence':('Strengthens growth as an edge beyond simple technology concentration; proceed only to independent implementation/regime robustness.' if passed else 'Do not treat P447 as independent growth-factor alpha; technology concentration explains enough of the apparent edge to fail the frozen residual-alpha gate. Preserve raw excess evidence but rotate without rescue.'),'boundaries':{'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}; OUT.write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps({'decision':out['decision'],'results':res},sort_keys=True))
