from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd
import p47_temporal_factor_discriminators_r1 as p47
import fixed_multifactor_cross_sectional_r1 as base

BP=50
WINDOWS={'2015_forward':'2015-01-01','2020_forward':'2020-01-01'}


def cagr(r):
    r=pd.Series(r,dtype=float).dropna(); return float((1+r).prod()**(12/len(r))-1) if len(r) else float('nan')


def build():
    close=base.load(p47.SYMBOLS); panel,m=p47.panel(close,p47.FACTORS); prev={s:0. for s in p47.SYMBOLS}; rows=[]
    for month in sorted(panel.month.unique()):
        b=panel[panel.month==month].sort_values(['score','symbol'],ascending=[False,True]); loc=m.index.get_loc(month)
        if len(b)!=len(p47.SYMBOLS) or not isinstance(loc,(int,np.integer)) or loc+1>=len(m): continue
        nxt=m.index[loc+1]; r=m.loc[nxt,list(p47.SYMBOLS)]/m.loc[month,list(p47.SYMBOLS)]-1
        if r.isna().any(): continue
        score=b.set_index('symbol').score.reindex(list(p47.SYMBOLS)); rank_ic=float(score.rank().corr(r.rank())); chosen=b.head(3).symbol.tolist(); rest=[s for s in p47.SYMBOLS if s not in chosen]
        w={s:(1/3 if s in chosen else 0.) for s in p47.SYMBOLS}; to=.5*sum(abs(w[s]-prev[s]) for s in p47.SYMBOLS); prev=w
        selected=float(r[chosen].mean()); rows.append({'date':nxt,'rank_ic':rank_ic,'spread':selected-float(r[rest].mean()),'candidate':selected-to*BP/10000,'ew':float(r.mean())})
    return pd.DataFrame(rows).set_index('date'),close


def evaluate(q):
    fs=[]
    for i,ids in enumerate(np.array_split(np.arange(len(q)),5),1):
        z=q.iloc[ids]; fs.append({'fold':i,'mean_rank_ic':float(z.rank_ic.mean()),'spread_mean':float(z.spread.mean()),'excess_cagr':cagr(z.candidate)-cagr(z.ew)})
    return {'months':len(q),'mean_rank_ic':float(q.rank_ic.mean()),'spread_mean':float(q.spread.mean()),'after_cost_excess_cagr':cagr(q.candidate)-cagr(q.ew),'positive_ic_folds':sum(x['mean_rank_ic']>0 for x in fs),'positive_spread_folds':sum(x['spread_mean']>0 for x in fs),'positive_excess_folds':sum(x['excess_cagr']>0 for x in fs),'folds':fs}


def main():
    q,close=build(); out={'schema':'research.p47_score_mechanism_r1','parent':'P47','hypothesis':'If P47 industry alpha is generated by the frozen four-factor ranking rather than only portfolio path, the score should positively rank next-month industry returns and selected top-3 industries should beat nonselected industries while retaining 50-bps matched excess.','scientific_contract':{'universe':'industry','factors':list(p47.FACTORS),'top_k':3,'cost_bps':BP,'matched_control':'same-universe equal weight','windows':WINDOWS,'chronological_folds':5,'no_parameter_tuning':True},'windows':{},'source':{'provider':'Yahoo Finance via yfinance; research-only','panel_sha256':base.source_hash(close)}}
    for name,start in WINDOWS.items(): out['windows'][name]=evaluate(q.loc[pd.Timestamp(start):])
    z=out['windows']['2020_forward']; out['decision']='P47_SCORE_MECHANISM_SUPPORTED' if z['mean_rank_ic']>0 and z['spread_mean']>0 and z['positive_ic_folds']>=3 and z['positive_spread_folds']>=3 else 'P47_SCORE_MECHANISM_WEAK'
    Path('artifacts').mkdir(exist_ok=True); Path('artifacts/p47_score_mechanism_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))
if __name__=='__main__': main()
