from __future__ import annotations
import io,json,math,urllib.request,zipfile,hashlib
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
OUT=Path('research/artifacts/p511_calf_ff5_independent_r1.json');OUT.parent.mkdir(parents=True,exist_ok=True)
URL='https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_CSV.zip';HURDLE=.0025
WINDOWS={'2018_plus':'2018-01-01','2020_plus':'2020-01-01','2022_plus':'2022-01-01'}
BLOCKS={'2018_2020':('2018-01-01','2020-12-31'),'2021_2023':('2021-01-01','2023-12-31'),'2024_plus':('2024-01-01',None)}
def ff5():
 d=urllib.request.urlopen(URL,timeout=30).read();z=zipfile.ZipFile(io.BytesIO(d));lines=z.read(z.namelist()[0]).decode('utf-8','replace').splitlines();s=next(i for i,x in enumerate(lines) if x.strip().startswith(',Mkt-RF'));e=next(i for i in range(s+1,len(lines)) if not lines[i].strip());f=pd.read_csv(io.StringIO('\n'.join(lines[s:e])));f=f.rename(columns={f.columns[0]:'ym'});f=f[f.ym.astype(str).str.fullmatch(r'\d{6}')];f.index=pd.to_datetime(f.ym.astype(str),format='%Y%m').dt.to_period('M').dt.to_timestamp('M');
 for k in ['Mkt-RF','SMB','HML','RMW','CMA','RF']:f[k]=pd.to_numeric(f[k],errors='coerce')/100
 return f[['Mkt-RF','SMB','HML','RMW','CMA','RF']].dropna(),d
f,fb=ff5();raw=yf.download(['CALF','IJS','IJR'],start='2017-01-01',end='2026-09-01',auto_adjust=True,progress=False,threads=False);c=(raw['Close'] if isinstance(raw.columns,pd.MultiIndex) else raw).resample('ME').last();r=c.pct_change(fill_method=None).join(f,how='inner').dropna()
def fit(t,start,end=None):
 q=r.loc[r.index>=pd.Timestamp(start)];
 if end:q=q.loc[q.index<=pd.Timestamp(end)]
 y=(q[t]-q.RF).to_numpy();X=np.column_stack([np.ones(len(q)),q[['Mkt-RF','SMB','HML','RMW','CMA']].to_numpy()]);b=np.linalg.lstsq(X,y,rcond=None)[0];res=y-X@b;n=len(y);s2=float(res@res/max(1,n-6));cov=s2*np.linalg.inv(X.T@X);se=float(np.sqrt(cov[0,0]));return {'months':n,'annualized_alpha_after_hurdle':float(b[0]*12-HURDLE),'alpha_t':float(b[0]/se) if se else None,'betas':{k:float(v) for k,v in zip(['Mkt-RF','SMB','HML','RMW','CMA'],b[1:])}}
def row(start,end=None):
 a=fit('CALF',start,end);i=fit('IJS',start,end);j=fit('IJR',start,end);return {'CALF':a,'IJS':i,'IJR':j,'CALF_minus_IJS_alpha':a['annualized_alpha_after_hurdle']-i['annualized_alpha_after_hurdle'],'CALF_minus_IJR_alpha':a['annualized_alpha_after_hurdle']-j['annualized_alpha_after_hurdle']}
w={k:row(v) for k,v in WINDOWS.items()};b={k:row(a,z) for k,(a,z) in BLOCKS.items()};s={'positive_calf_windows':sum(w[k]['CALF']['annualized_alpha_after_hurdle']>0 for k in w),'positive_calf_blocks':sum(b[k]['CALF']['annualized_alpha_after_hurdle']>0 for k in b),'beats_ijs_windows':sum(w[k]['CALF_minus_IJS_alpha']>0 for k in w),'beats_ijs_blocks':sum(b[k]['CALF_minus_IJS_alpha']>0 for k in b)};ok=s['positive_calf_windows']==3 and s['positive_calf_blocks']>=2 and s['beats_ijs_windows']==3 and s['beats_ijs_blocks']>=2;dec='CALF_INDEPENDENT_FF5_SUPPORTED' if ok else 'CALF_INDEPENDENT_FF5_NOT_SUPPORTED'
out={'schema':'research.p511_calf_ff5_independent_r1.v1','workload_id':'P511_CALF_FF5_INDEPENDENT_R1','parent':'FREE_CASH_FLOW_YIELD_FACTOR/CALF_SCOPED','claim':'Independent academic-factor falsifier of the P510 CALF small-cap free-cash-flow candidate using Ken French FF5 monthly data, with IJS and IJR comparator alphas. Fixed 25bp annual hurdle, windows and chronology; no factor/date/comparator/hurdle rescue.','sources':{'ff5_url':URL,'ff5_zip_sha256':hashlib.sha256(fb).hexdigest(),'price_source':'Yahoo adjusted prices through completed month 2026-08-31'},'contract':{'candidate':'CALF','comparators':['IJS','IJR'],'factors':['Mkt-RF','SMB','HML','RMW','CMA'],'annual_hurdle_bps':25,'windows':WINDOWS,'blocks':BLOCKS,'support_rule':'CALF positive after-hurdle FF5 alpha 3/3 windows and >=2/3 blocks; CALF alpha exceeds IJS 3/3 windows and >=2/3 blocks','no_factor_date_comparator_hurdle_or_threshold_search':True},'windows':w,'blocks':b,'summary':s,'decision':dec,'scientific_consequence':'If supported, promote CALF as a scoped small-cap FCF candidate with independent factor-attribution support. If not, downgrade the P510 observation and rotate without factor/window/comparator rescue.','boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
OUT.write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False));print(json.dumps({'decision':dec,'summary':s,'windows':{k:{'calf_alpha_pp':round(v['CALF']['annualized_alpha_after_hurdle']*100,3),'vs_ijs_pp':round(v['CALF_minus_IJS_alpha']*100,3),'t':round(v['CALF']['alpha_t'],2)} for k,v in w.items()},'blocks':{k:{'calf_alpha_pp':round(v['CALF']['annualized_alpha_after_hurdle']*100,3),'vs_ijs_pp':round(v['CALF_minus_IJS_alpha']*100,3)} for k,v in b.items()}},sort_keys=True))
