from __future__ import annotations
import json,math
from pathlib import Path
import numpy as np,pandas as pd,yfinance as yf
CROSS=("SPY","QQQ","TLT","GLD","DBC"); IND=("SMH","XBI","ITB","KRE","ITA","IGV","IWM","XRT"); ALL=tuple(dict.fromkeys((*CROSS,*IND))); START="2006-01-01"
def metrics(r):
 r=pd.Series(r,dtype=float).dropna(); e=(1+r).cumprod(); y=len(r)/12; c=float(e.iloc[-1]**(1/y)-1); a=float(r.mean()*12); v=float(r.std(ddof=0)*math.sqrt(12)); dd=e/e.cummax()-1; m=float(dd.min()); return {'cagr':c,'annualized_mean':a,'annualized_vol':v,'sharpe_rf0':a/v if v else float('nan'),'max_drawdown_monthly':m,'calmar':c/abs(m) if m<0 else float('nan')}
def fold_count(c,b):
 out=[]
 for n,idx in enumerate(np.array_split(np.arange(len(c)),5),1):
  x,y=metrics(c.iloc[idx]),metrics(b.iloc[idx]); out.append({'fold':n,'excess_cagr':x['cagr']-y['cagr']})
 return sum(z['excess_cagr']>0 for z in out),out
def main():
 d=yf.download(list(ALL),start=START,auto_adjust=True,progress=False,threads=False); close=d['Close'] if isinstance(d.columns,pd.MultiIndex) else d[['Close']]; close=close.loc[:,list(ALL)].dropna(how='all').astype(float); m=close.resample('ME').last(); last=pd.Timestamp(close.index.max()); last=last.tz_localize(None) if last.tzinfo is not None else last; m=m.loc[m.index<=last.normalize()]; dr=close.pct_change(); vol=(dr.rolling(126,min_periods=100).std(ddof=0)*math.sqrt(252)).resample('ME').last(); trend=(close/close.rolling(200,min_periods=160).mean()-1).resample('ME').last(); dd=(close/close.rolling(126,min_periods=100).max()-1).resample('ME').last(); mom=m.pct_change(6); pc={s:0. for s in CROSS}; pi={s:0. for s in IND}; rows=[]
 for dt in m.index:
  bc=pd.DataFrame({'mom6':mom.loc[dt,list(CROSS)],'trend200':trend.loc[dt,list(CROSS)],'low_vol6':-vol.loc[dt,list(CROSS)],'drawdown6':dd.loc[dt,list(CROSS)]},index=list(CROSS)); bi=pd.DataFrame({'mom6':mom.loc[dt,list(IND)],'trend200':trend.loc[dt,list(IND)],'low_vol6':-vol.loc[dt,list(IND)],'drawdown6':dd.loc[dt,list(IND)]},index=list(IND))
  if bc.isna().any().any() or bi.isna().any().any(): continue
  loc=m.index.get_loc(dt)
  if not isinstance(loc,(int,np.integer)) or loc+1>=len(m): continue
  nxt=m.index[loc+1]; r=m.loc[nxt,list(ALL)]/m.loc[dt,list(ALL)]-1
  if r.isna().any(): continue
  cc=bc.rank(axis=0,pct=True,method='average').mean(axis=1).sort_values(ascending=False).head(2).index; ci=bi.rank(axis=0,pct=True,method='average').mean(axis=1).sort_values(ascending=False).head(3).index; wc={s:(.5 if s in cc else 0.) for s in CROSS}; wi={s:(1/3 if s in ci else 0.) for s in IND}; tc=.5*sum(abs(wc[s]-pc[s]) for s in CROSS); ti=.5*sum(abs(wi[s]-pi[s]) for s in IND); gc=sum(wc[s]*float(r[s]) for s in CROSS); gi=sum(wi[s]*float(r[s]) for s in IND); ewc=float(r.loc[list(CROSS)].mean()); ewi=float(r.loc[list(IND)].mean()); rows.append({'date':nxt,'cross_gross':gc,'industry_gross':gi,'cross_turnover':tc,'industry_turnover':ti,'ensemble_gross':.5*gc+.5*gi,'control':.5*ewc+.5*ewi,'spy':float(r['SPY']),'qqq':float(r['QQQ'])}); pc,pi=wc,wi
 f=pd.DataFrame(rows).set_index('date'); costs={}
 for bps in (25,50):
  cross=f.cross_gross-f.cross_turnover*bps/10000; ind=f.industry_gross-f.industry_turnover*bps/10000; ens=.5*cross+.5*ind; ctrl=f.control; em,cm,im,bm=metrics(ens),metrics(cross),metrics(ind),metrics(ctrl); p,fs=fold_count(ens,ctrl); ex_cross=ens-cross; ex_ind=ens-ind; costs[str(bps)]={'ensemble':em,'cross_parent':cm,'industry_parent':im,'matched_control':bm,'spy':metrics(f.spy),'qqq':metrics(f.qqq),'excess_cagr_vs_matched_control':em['cagr']-bm['cagr'],'excess_cagr_vs_cross_parent':em['cagr']-cm['cagr'],'excess_cagr_vs_industry_parent':em['cagr']-im['cagr'],'positive_folds_vs_matched_control':p,'folds':fs,'monthly_parent_return_correlation':float(cross.corr(ind))}
 p25,p50=costs['25'],costs['50']; support=p25['excess_cagr_vs_matched_control']>0 and p25['positive_folds_vs_matched_control']>=3 and p50['excess_cagr_vs_matched_control']>0 and p25['ensemble']['sharpe_rf0']>=min(p25['cross_parent']['sharpe_rf0'],p25['industry_parent']['sharpe_rf0']) and p25['ensemble']['max_drawdown_monthly']>=min(p25['cross_parent']['max_drawdown_monthly'],p25['industry_parent']['max_drawdown_monthly'])
 out={'schema':'research.p89_p46_p47_research_ensemble_r1','parent_ids':['P46','P47','P89'],'scientific_contract':{'scope':'research-only model-combination discriminator; no portfolio allocation authority','ensemble':'static 50/50 of original frozen P46 cross-asset and P47 industry net return streams','matched_control':'static 50/50 of each parent exact equal-weight universe control','costs_bps':[25,50],'opportunity_cost':['each parent','SPY','QQQ'],'no_weight_or_parent_tuning':True},'window':{'start':str(f.index.min().date()),'end':str(f.index.max().date()),'months':len(f)},'turnover':{'cross_annual':float(f.cross_turnover.mean()*12),'industry_annual':float(f.industry_turnover.mean()*12)},'costs':costs,'decision':'SUPPORTED_RESEARCH_ENSEMBLE_DIVERSIFICATION' if support else 'ENSEMBLE_NOT_ADDITIVE_KEEP_PARENTS_SEPARATE'}; Path('artifacts').mkdir(exist_ok=True); Path('artifacts/p89_p46_p47_research_ensemble_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps({'decision':out['decision'],'window':out['window'],'25':{'excess_vs_control':p25['excess_cagr_vs_matched_control'],'excess_vs_cross':p25['excess_cagr_vs_cross_parent'],'excess_vs_industry':p25['excess_cagr_vs_industry_parent'],'folds':p25['positive_folds_vs_matched_control'],'ensemble':p25['ensemble'],'cross':p25['cross_parent'],'industry':p25['industry_parent'],'correlation':p25['monthly_parent_return_correlation']},'50':{'excess_vs_control':p50['excess_cagr_vs_matched_control']}},sort_keys=True))
if __name__=='__main__': main()
