from __future__ import annotations
import json, urllib.request
from pathlib import Path
UA='XoticHaze market-research source-validation contact@example.com'; CURRENT_CIK='0002115436'; LEGACY_CIK='0000034088'
def get(url):
 req=urllib.request.Request(url,headers={'User-Agent':UA,'Accept':'application/json'}); return json.loads(urllib.request.urlopen(req,timeout=30).read().decode())
def summarize(cik):
 sub=get(f'https://data.sec.gov/submissions/CIK{cik}.json'); facts=get(f'https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json'); rec=sub.get('filings',{}).get('recent',{}); dates=rec.get('filingDate',[]); forms=rec.get('form',[]); acc=rec.get('accessionNumber',[])
 recent=[{'form':forms[i] if i<len(forms) else None,'filing_date':dates[i] if i<len(dates) else None,'accession':acc[i] if i<len(acc) else None} for i in range(max(len(forms),len(dates),len(acc)))]
 fd=[]
 for concept in facts.get('facts',{}).get('us-gaap',{}).values():
  for vals in concept.get('units',{}).values():
   fd += [v['filed'] for v in vals if v.get('filed')]
 return {'cik':cik,'submission_name':sub.get('name'),'tickers':sub.get('tickers',[]),'exchanges':sub.get('exchanges',[]),'former_names':sub.get('formerNames',[]),'recent_filings':recent[:40],'companyfacts_entity_name':facts.get('entityName'),'companyfacts_first_filed':min(fd) if fd else None,'companyfacts_last_filed':max(fd) if fd else None,'companyfacts_filed_count':len(fd)}
mapping=get('https://www.sec.gov/files/company_tickers.json'); xom=[v for v in mapping.values() if v.get('ticker','').upper()=='XOM']; current=summarize(CURRENT_CIK); legacy=summarize(LEGACY_CIK); mapped=sorted({str(v['cik_str']).zfill(10) for v in xom})
longhist=bool(legacy['companyfacts_first_filed'] and legacy['companyfacts_first_filed']<'2012-01-01' and legacy['companyfacts_last_filed']>='2026-01-01'); recent=bool(current['companyfacts_first_filed'] and current['companyfacts_first_filed']>='2026-01-01'); successor_xom='XOM' in current['tickers']; exit_form=any(x.get('form')=='25-NSE' for x in legacy['recent_filings']); names=('EXXON MOBIL' in (legacy['submission_name'] or '').upper() and 'EXXONMOBIL' in (current['submission_name'] or '').replace(' ','').upper()); chronology=bool(legacy['companyfacts_last_filed'] and current['companyfacts_first_filed'] and legacy['companyfacts_last_filed']<=current['companyfacts_first_filed']); ok=longhist and recent and successor_xom and exit_form and names and chronology and CURRENT_CIK in mapped
out={'schema':'research.sec_issuer_continuity_adjudicator_r2','workload_id':'SEC_ISSUER_CONTINUITY_ADJUDICATOR_R2','parent_context':'P287','claim':'Determine whether P287 remaining XOM coverage failure is a current ticker-to-CIK corporate-identity transition rather than absent SEC filed-at history. Do not require a retired predecessor CIK to keep advertising the successor ticker.','company_tickers_xom_rows':xom,'current_mapping_ciks':mapped,'current_mapped_entity':current,'legacy_long_history_entity':legacy,'tests':{'legacy_has_pre2012_through_2026_facts':longhist,'current_mapped_cik_is_2026_recent':recent,'current_successor_reports_XOM':successor_xom,'legacy_has_25_NSE_exit_filing':exit_form,'entity_name_continuity':names,'fact_chronology_nonoverlap':chronology,'current_company_tickers_contains_recent_cik':CURRENT_CIK in mapped},'decision':'SEC_XOM_CIK_TRANSITION_CONFIRMED__LINEAGE_LAYER_REQUIRED' if ok else 'SEC_XOM_CIK_TRANSITION_NOT_CONFIRMED','decision_rule':'Confirm only if predecessor has long history through 2026, successor begins in 2026 and carries XOM, predecessor has 25-NSE exit evidence, Exxon Mobil identity is continuous, and predecessor facts end no later than successor facts begin.','scientific_consequence':'If confirmed, preserve SEC companyfacts source feasibility but require deterministic corporate-action/issuer-lineage authority before historical cross-sectional alpha inference. Do not drop XOM, union CIKs ad hoc, or use current ticker mapping as historical membership authority.','r1_correction':'R1 circularly required both predecessor and successor submission records to simultaneously report XOM. R2 uses exit-form, name-continuity, successor-ticker, and nonoverlapping fact chronology evidence instead.','boundaries':{'scientific_authority':True,'portfolio_ranking':False,'allocation_authority':False,'runtime':False,'broker':False,'live_trading':False}}
Path('research/artifacts').mkdir(parents=True,exist_ok=True); Path('research/artifacts/sec_issuer_continuity_adjudicator_r1.json').write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)); print(json.dumps(out,sort_keys=True))
