from __future__ import annotations

"""Encrypted public-compute consumer for the frozen semiconductor forward observer.

V2 adds an economic parity gate against the immutable 2026-09-04 reference before a
current observation may be generated. The public repository never stores private model
source or forecast plaintext. A one-run X25519 recipient is generated by the workflow;
the private authority encrypts an exact hash-bound source capsule to that recipient.
Execution occurs only in runner temp and the result is encrypted to a distinct private
return recipient embedded in the encrypted capsule.
"""

import argparse
import base64
import hashlib
import io
import json
import math
import os
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

SCHEMA = "semiconductor-forward-ephemeral-x25519-v2"
RETURN_SCHEMA = "semiconductor-forward-return-x25519-v2"
HARNESS = "semiconductor_entry_value_model_forward_v2"
INFO = b"research-foundry-semiconductor-forward-ephemeral-v2"
RETURN_INFO = b"research-foundry-semiconductor-forward-return-v2"
PAYLOAD_SCHEMA = "research-foundry-semiconductor-forward-payload-v2"
PARITY_ASOF = "2026-09-04"
FLOAT_TOL = 1e-8
ALLOWED_FILES = {
    "research/semiconductor_external_forward_standalone_20260910.py",
    "research/semiconductor_three_book_forward_contract_20260910.json",
    "research/semiconductor_three_book_forward_20260910.py",
    "research/semiconductor_external_forward_reference_20260904.json",
}


def _b64d(value: str) -> bytes:
    return base64.b64decode(value.encode("ascii"), validate=True)


def _key_id(public_raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(public_raw).hexdigest()


def _aad(schema: str, run_id: str, recipient_key_id: str, harness: str) -> bytes:
    return json.dumps(
        {
            "schema": schema,
            "run_id": str(run_id),
            "authority": "research_only",
            "harness": harness,
            "recipient_key_id": recipient_key_id,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _derive(shared: bytes, aad: bytes, info: bytes) -> bytes:
    return HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=hashlib.sha256(aad).digest(),
        info=info,
    ).derive(shared)


def _decrypt_input(envelope: dict, private_raw: bytes, run_id: str) -> bytes:
    required = {
        "schema",
        "run_id",
        "authority",
        "harness",
        "recipient_key_id",
        "sender_public_b64",
        "nonce_b64",
        "ciphertext_b64",
        "plaintext_sha256",
    }
    if set(envelope) != required:
        raise RuntimeError("input envelope field-set mismatch")
    if envelope["schema"] != SCHEMA or str(envelope["run_id"]) != str(run_id):
        raise RuntimeError("input run identity mismatch")
    if envelope["authority"] != "research_only" or envelope["harness"] != HARNESS:
        raise RuntimeError("input authority/harness mismatch")
    private = x25519.X25519PrivateKey.from_private_bytes(private_raw)
    recipient_raw = private.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    expected_id = _key_id(recipient_raw)
    if envelope["recipient_key_id"] != expected_id:
        raise RuntimeError("input recipient fingerprint mismatch")
    sender_raw = _b64d(envelope["sender_public_b64"])
    nonce = _b64d(envelope["nonce_b64"])
    ciphertext = _b64d(envelope["ciphertext_b64"])
    if len(sender_raw) != 32 or len(nonce) != 12:
        raise RuntimeError("input key/nonce shape invalid")
    aad = _aad(SCHEMA, run_id, expected_id, HARNESS)
    shared = private.exchange(x25519.X25519PublicKey.from_public_bytes(sender_raw))
    plaintext = ChaCha20Poly1305(_derive(shared, aad, INFO)).decrypt(nonce, ciphertext, aad)
    if hashlib.sha256(plaintext).hexdigest() != envelope["plaintext_sha256"]:
        raise RuntimeError("input plaintext digest mismatch")
    return plaintext


def _safe_extract(payload: bytes, root: Path) -> dict:
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as archive:
        members = archive.getmembers()
        names = {member.name for member in members if member.isfile()}
        expected = {"payload-manifest.json", *ALLOWED_FILES}
        if names != expected:
            raise RuntimeError(f"payload file-set mismatch: {sorted(names ^ expected)}")
        for member in members:
            if not member.isfile():
                continue
            relative = Path(member.name)
            if relative.is_absolute() or ".." in relative.parts:
                raise RuntimeError("unsafe payload path")
            source = archive.extractfile(member)
            if source is None:
                raise RuntimeError(f"unable to read {member.name}")
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(source.read())
    manifest = json.loads((root / "payload-manifest.json").read_text(encoding="utf-8"))
    if manifest.get("schema") != PAYLOAD_SCHEMA or manifest.get("harness") != HARNESS:
        raise RuntimeError("payload manifest identity mismatch")
    hashes_expected = manifest.get("files") or {}
    if set(hashes_expected) != ALLOWED_FILES:
        raise RuntimeError("payload manifest file-set mismatch")
    for relative, expected_hash in hashes_expected.items():
        actual = hashlib.sha256((root / relative).read_bytes()).hexdigest()
        if actual != expected_hash:
            raise RuntimeError(f"payload digest mismatch: {relative}")
    return manifest


def _observer(root: Path, output: Path, *, asof: str | None = None) -> None:
    env = dict(os.environ)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    output.parent.mkdir(parents=True, exist_ok=True)
    command = [
        sys.executable,
        "-m",
        "research.semiconductor_external_forward_standalone_20260910",
    ]
    if asof is not None:
        command.extend(["--asof", asof])
    command.extend(["--output", str(output.relative_to(root))])
    run = subprocess.run(
        command,
        cwd=root,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=900,
        check=False,
    )
    if run.returncode != 0:
        label = "parity observer" if asof is not None else "current observer"
        raise RuntimeError(f"{label} failed rc={run.returncode}")
    if not output.is_file():
        raise RuntimeError("observer output missing")


def _float_diff(actual: object, expected: object, field: str) -> float:
    a = float(actual)
    e = float(expected)
    if not math.isfinite(a) or not math.isfinite(e):
        raise RuntimeError(f"nonfinite parity field {field}")
    diff = abs(a - e)
    if diff > FLOAT_TOL:
        raise RuntimeError(f"parity mismatch {field}: abs_diff={diff}")
    return diff


def _parity(actual: dict, reference: dict) -> dict:
    exact_top = ("schema", "generation_bar_date", "common_calendar_rows")
    for field in exact_top:
        if actual.get(field) != reference.get(field):
            raise RuntimeError(f"parity mismatch top-level {field}")
    for field in (
        "month",
        "fit_anchor_date",
        "safe_last_training_signal_date",
        "resolved_session_purge",
        "training_rows",
        "train_universe",
        "external_target_rows",
    ):
        if (actual.get("monthly_fit") or {}).get(field) != (reference.get("monthly_fit") or {}).get(field):
            raise RuntimeError(f"parity mismatch monthly_fit.{field}")

    actual_rows = {str(row["symbol"]): row for row in actual.get("observations") or []}
    expected_rows = {str(row["symbol"]): row for row in reference.get("observations") or []}
    if set(actual_rows) != set(expected_rows):
        raise RuntimeError("parity observation symbol set mismatch")

    max_prediction_diff = 0.0
    max_feature_diff = 0.0
    exact_fields = (
        "bar_date",
        "descriptive_value_rank",
        "external_target_history_used_in_fit",
        "frozen_top30_signal",
        "positive_value_opportunity",
        "role",
        "symbol",
    )
    float_fields = ("predicted_fixed20_net_value_bps", "mom20", "prior_top30_threshold")
    for symbol in sorted(expected_rows):
        arow = actual_rows[symbol]
        erow = expected_rows[symbol]
        for field in exact_fields:
            if arow.get(field) != erow.get(field):
                raise RuntimeError(f"parity mismatch {symbol}.{field}")
        for field in float_fields:
            diff = _float_diff(arow.get(field), erow.get(field), f"{symbol}.{field}")
            if field == "predicted_fixed20_net_value_bps":
                max_prediction_diff = max(max_prediction_diff, diff)
            else:
                max_feature_diff = max(max_feature_diff, diff)

    return {
        "status": "PASS",
        "reference_date": PARITY_ASOF,
        "symbol_count": len(expected_rows),
        "float_tolerance": FLOAT_TOL,
        "max_abs_prediction_bps_diff": max_prediction_diff,
        "max_abs_feature_diff": max_feature_diff,
    }


def _run_private_harness(root: Path) -> tuple[bytes, dict]:
    parity_path = root / "research/results/semiconductor_external_forward/parity-2026-09-04.json"
    _observer(root, parity_path, asof=PARITY_ASOF)
    parity_prediction = json.loads(parity_path.read_text(encoding="utf-8"))
    reference_path = root / "research/semiconductor_external_forward_reference_20260904.json"
    reference = json.loads(reference_path.read_text(encoding="utf-8"))
    parity = _parity(parity_prediction, reference)

    prediction_path = root / "research/results/semiconductor_external_forward/current.json"
    _observer(root, prediction_path)
    prediction = json.loads(prediction_path.read_text(encoding="utf-8"))
    generation = str(prediction["generation_bar_date"])
    contract = json.loads(
        (root / "research/semiconductor_three_book_forward_contract_20260910.json").read_text(
            encoding="utf-8"
        )
    )
    book_path = root / "research/results/semiconductor_three_book_forward" / f"{generation}.json"
    book_status = "PRESTART_NO_BOOK"
    if generation >= str(contract["prospective_start_signal_date"]):
        book_path.parent.mkdir(parents=True, exist_ok=True)
        env = dict(os.environ)
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        run = subprocess.run(
            [
                sys.executable,
                "-m",
                "research.semiconductor_three_book_forward_20260910",
                "--prediction",
                str(prediction_path.relative_to(root)),
                "--contract",
                "research/semiconductor_three_book_forward_contract_20260910.json",
                "--output",
                str(book_path.relative_to(root)),
            ],
            cwd=root,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=900,
            check=False,
        )
        if run.returncode != 0:
            raise RuntimeError(f"three-book constructor failed rc={run.returncode}")
        if not book_path.is_file():
            raise RuntimeError("three-book output missing")
        book_status = "PAPER_BOOK_CREATED"

    receipt = {
        "schema": "semiconductor-forward-public-compute-receipt-v2",
        "authority": "research_only",
        "harness": HARNESS,
        "generation_bar_date": generation,
        "prediction_sha256": hashlib.sha256(prediction_path.read_bytes()).hexdigest(),
        "parity": parity,
        "book_status": book_status,
        "book_sha256": hashlib.sha256(book_path.read_bytes()).hexdigest() if book_path.is_file() else None,
        "private_stdout_exposed": False,
        "private_stderr_exposed": False,
        "private_source_persisted": False,
    }

    output_buffer = io.BytesIO()
    with tarfile.open(fileobj=output_buffer, mode="w:gz", format=tarfile.PAX_FORMAT) as archive:
        files: list[tuple[str, Path | None]] = [
            ("prediction.json", prediction_path),
            ("paper-book.json", book_path if book_path.is_file() else None),
            ("receipt.json", None),
        ]
        for archive_name, path in files:
            if archive_name == "receipt.json":
                data = (json.dumps(receipt, sort_keys=True, indent=2) + "\n").encode("utf-8")
            elif path is not None:
                data = path.read_bytes()
            else:
                continue
            info = tarfile.TarInfo(archive_name)
            info.size = len(data)
            info.mtime = 0
            archive.addfile(info, io.BytesIO(data))
    return output_buffer.getvalue(), receipt


def _encrypt_return(payload: bytes, manifest: dict, run_id: str) -> dict:
    recipient_raw = _b64d(str(manifest["return_recipient_b64"]))
    if len(recipient_raw) != 32:
        raise RuntimeError("return recipient public key invalid")
    key_id = _key_id(recipient_raw)
    if manifest.get("return_recipient_key_id") != key_id:
        raise RuntimeError("return recipient fingerprint mismatch")
    sender = x25519.X25519PrivateKey.generate()
    sender_public = sender.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    aad = _aad(RETURN_SCHEMA, run_id, key_id, HARNESS)
    shared = sender.exchange(x25519.X25519PublicKey.from_public_bytes(recipient_raw))
    nonce = os.urandom(12)
    ciphertext = ChaCha20Poly1305(_derive(shared, aad, RETURN_INFO)).encrypt(nonce, payload, aad)
    return {
        "schema": RETURN_SCHEMA,
        "run_id": str(run_id),
        "authority": "research_only",
        "harness": HARNESS,
        "recipient_key_id": key_id,
        "sender_public_b64": base64.b64encode(sender_public).decode("ascii"),
        "nonce_b64": base64.b64encode(nonce).decode("ascii"),
        "ciphertext_b64": base64.b64encode(ciphertext).decode("ascii"),
        "plaintext_sha256": hashlib.sha256(payload).hexdigest(),
    }


def consume(envelope_path: Path, private_key_path: Path, expected_run_id: str, output: Path) -> dict:
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))
    private_raw = _b64d(private_key_path.read_text(encoding="ascii").strip())
    if len(private_raw) != 32:
        raise RuntimeError("input recipient private key invalid")
    plaintext = _decrypt_input(envelope, private_raw, expected_run_id)
    with tempfile.TemporaryDirectory(prefix="semiconductor-forward-v2-") as temp:
        root = Path(temp)
        manifest = _safe_extract(plaintext, root)
        return_payload, receipt = _run_private_harness(root)
        return_envelope = _encrypt_return(return_payload, manifest, expected_run_id)
        output.write_text(json.dumps(return_envelope, sort_keys=True) + "\n", encoding="utf-8")
        return receipt


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--envelope", required=True)
    parser.add_argument("--private-key", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--return-envelope", required=True)
    args = parser.parse_args()
    receipt = consume(
        Path(args.envelope),
        Path(args.private_key),
        args.run_id,
        Path(args.return_envelope),
    )
    print("SEMICONDUCTOR_FORWARD_PUBLIC_RECEIPT=" + json.dumps(receipt, sort_keys=True))


if __name__ == "__main__":
    main()
