from __future__ import annotations

"""Encrypted public-compute consumer for the frozen semiconductor forward observer.

The public repository never stores the private model source in plaintext. A one-run
X25519 recipient is generated by the workflow. The private authority encrypts an exact,
hash-bound source capsule to that recipient. This consumer decrypts only in runner temp,
executes the fixed research harness, then encrypts the private forecast/book outputs to a
return recipient contained inside the encrypted capsule. Public output is receipt-only.
"""

import argparse
import base64
import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

SCHEMA = "semiconductor-forward-ephemeral-x25519-v1"
RETURN_SCHEMA = "semiconductor-forward-return-x25519-v1"
HARNESS = "semiconductor_external_forward_three_book_v1"
INFO = b"research-foundry-semiconductor-forward-ephemeral-v1"
RETURN_INFO = b"research-foundry-semiconductor-forward-return-v1"
PAYLOAD_SCHEMA = "research-foundry-semiconductor-forward-payload-v1"
ALLOWED_FILES = {
    "research/run_semiconductor_external_forward_20260904.py",
    "research/run_survivor_entry_external_transport_20260902.py",
    "research/run_survivor_entry_value_20260902.py",
    "research/run_survivor_fixed10_vs20_capital_20260902.py",
    "research/semiconductor_three_book_forward_contract_20260910.json",
    "research/semiconductor_three_book_forward_20260910.py",
}


def _b64d(value: str) -> bytes:
    return base64.b64decode(value.encode("ascii"), validate=True)


def _key_id(public_raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(public_raw).hexdigest()


def _aad(schema: str, run_id: str, recipient_key_id: str, harness: str) -> bytes:
    return json.dumps(
        {
            "schema": schema,
            "run_id": str(run_id),
            "authority": "research_only",
            "harness": harness,
            "recipient_key_id": recipient_key_id,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _derive(shared: bytes, aad: bytes, info: bytes) -> bytes:
    return HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=hashlib.sha256(aad).digest(),
        info=info,
    ).derive(shared)


def _decrypt_input(envelope: dict, private_raw: bytes, run_id: str) -> bytes:
    required = {
        "schema",
        "run_id",
        "authority",
        "harness",
        "recipient_key_id",
        "sender_public_b64",
        "nonce_b64",
        "ciphertext_b64",
        "plaintext_sha256",
    }
    if set(envelope) != required:
        raise RuntimeError("input envelope field-set mismatch")
    if envelope["schema"] != SCHEMA or str(envelope["run_id"]) != str(run_id):
        raise RuntimeError("input run identity mismatch")
    if envelope["authority"] != "research_only" or envelope["harness"] != HARNESS:
        raise RuntimeError("input authority/harness mismatch")
    private = x25519.X25519PrivateKey.from_private_bytes(private_raw)
    recipient_raw = private.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    expected_id = _key_id(recipient_raw)
    if envelope["recipient_key_id"] != expected_id:
        raise RuntimeError("input recipient fingerprint mismatch")
    sender_raw = _b64d(envelope["sender_public_b64"])
    nonce = _b64d(envelope["nonce_b64"])
    ciphertext = _b64d(envelope["ciphertext_b64"])
    if len(sender_raw) != 32 or len(nonce) != 12:
        raise RuntimeError("input key/nonce shape invalid")
    aad = _aad(SCHEMA, run_id, expected_id, HARNESS)
    shared = private.exchange(x25519.X25519PublicKey.from_public_bytes(sender_raw))
    plaintext = ChaCha20Poly1305(_derive(shared, aad, INFO)).decrypt(nonce, ciphertext, aad)
    if hashlib.sha256(plaintext).hexdigest() != envelope["plaintext_sha256"]:
        raise RuntimeError("input plaintext digest mismatch")
    return plaintext


def _safe_extract(payload: bytes, root: Path) -> dict:
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as tf:
        members = tf.getmembers()
        names = {member.name for member in members if member.isfile()}
        expected = {"payload-manifest.json", *ALLOWED_FILES}
        if names != expected:
            raise RuntimeError(f"payload file-set mismatch: {sorted(names ^ expected)}")
        for member in members:
            if not member.isfile():
                continue
            rel = Path(member.name)
            if rel.is_absolute() or ".." in rel.parts:
                raise RuntimeError("unsafe payload path")
            target = root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            src = tf.extractfile(member)
            if src is None:
                raise RuntimeError(f"unable to read {member.name}")
            target.write_bytes(src.read())
    manifest = json.loads((root / "payload-manifest.json").read_text(encoding="utf-8"))
    if manifest.get("schema") != PAYLOAD_SCHEMA or manifest.get("harness") != HARNESS:
        raise RuntimeError("payload manifest identity mismatch")
    hashes_expected = manifest.get("files") or {}
    if set(hashes_expected) != ALLOWED_FILES:
        raise RuntimeError("payload manifest file-set mismatch")
    for rel, expected_hash in hashes_expected.items():
        actual = hashlib.sha256((root / rel).read_bytes()).hexdigest()
        if actual != expected_hash:
            raise RuntimeError(f"payload digest mismatch: {rel}")
    return manifest


def _run_private_harness(root: Path) -> tuple[bytes, dict]:
    env = dict(os.environ)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    observer = subprocess.run(
        [sys.executable, "-m", "research.run_semiconductor_external_forward_20260904"],
        cwd=root,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=900,
        check=False,
    )
    if observer.returncode != 0:
        raise RuntimeError(
            "frozen observer failed: " + observer.stderr[-2000:].replace("\n", " | ")
        )
    predictions = sorted(
        (root / "research/results/semiconductor_external_forward").glob("*.json")
    )
    if len(predictions) != 1:
        raise RuntimeError(f"expected one prediction receipt, got {len(predictions)}")
    prediction_path = predictions[0]
    prediction = json.loads(prediction_path.read_text(encoding="utf-8"))
    generation = str(prediction["generation_bar_date"])
    contract = json.loads(
        (root / "research/semiconductor_three_book_forward_contract_20260910.json").read_text(
            encoding="utf-8"
        )
    )
    book_path = root / "research/results/semiconductor_three_book_forward" / f"{generation}.json"
    book_status = "PRESTART_NO_BOOK"
    if generation >= str(contract["prospective_start_signal_date"]):
        book_path.parent.mkdir(parents=True, exist_ok=True)
        book = subprocess.run(
            [
                sys.executable,
                "-m",
                "research.semiconductor_three_book_forward_20260910",
                "--prediction",
                str(prediction_path.relative_to(root)),
                "--contract",
                "research/semiconductor_three_book_forward_contract_20260910.json",
                "--output",
                str(book_path.relative_to(root)),
            ],
            cwd=root,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=900,
            check=False,
        )
        if book.returncode != 0:
            raise RuntimeError("three-book constructor failed: " + book.stderr[-2000:].replace("\n", " | "))
        if not book_path.is_file():
            raise RuntimeError("three-book output missing")
        book_status = "PAPER_BOOK_CREATED"

    receipt = {
        "schema": "semiconductor-forward-public-compute-receipt-v1",
        "authority": "research_only",
        "harness": HARNESS,
        "generation_bar_date": generation,
        "prediction_sha256": hashlib.sha256(prediction_path.read_bytes()).hexdigest(),
        "book_status": book_status,
        "book_sha256": hashlib.sha256(book_path.read_bytes()).hexdigest() if book_path.is_file() else None,
        "private_stdout_exposed": False,
        "private_source_persisted": False,
    }
    output_buf = io.BytesIO()
    with tarfile.open(fileobj=output_buf, mode="w:gz", format=tarfile.PAX_FORMAT) as tf:
        for arcname, path in [
            ("prediction.json", prediction_path),
            ("paper-book.json", book_path if book_path.is_file() else None),
        ]:
            if path is None:
                continue
            data = path.read_bytes()
            info = tarfile.TarInfo(arcname)
            info.size = len(data)
            info.mtime = 0
            tf.addfile(info, io.BytesIO(data))
        receipt_data = (json.dumps(receipt, sort_keys=True, indent=2) + "\n").encode("utf-8")
        info = tarfile.TarInfo("receipt.json")
        info.size = len(receipt_data)
        info.mtime = 0
        tf.addfile(info, io.BytesIO(receipt_data))
    return output_buf.getvalue(), receipt


def _encrypt_return(payload: bytes, manifest: dict, run_id: str) -> dict:
    recipient_raw = _b64d(str(manifest["return_recipient_b64"]))
    if len(recipient_raw) != 32:
        raise RuntimeError("return recipient public key invalid")
    key_id = _key_id(recipient_raw)
    if manifest.get("return_recipient_key_id") != key_id:
        raise RuntimeError("return recipient fingerprint mismatch")
    sender = x25519.X25519PrivateKey.generate()
    sender_public = sender.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    aad = _aad(RETURN_SCHEMA, run_id, key_id, HARNESS)
    shared = sender.exchange(x25519.X25519PublicKey.from_public_bytes(recipient_raw))
    nonce = os.urandom(12)
    ciphertext = ChaCha20Poly1305(_derive(shared, aad, RETURN_INFO)).encrypt(nonce, payload, aad)
    return {
        "schema": RETURN_SCHEMA,
        "run_id": str(run_id),
        "authority": "research_only",
        "harness": HARNESS,
        "recipient_key_id": key_id,
        "sender_public_b64": base64.b64encode(sender_public).decode("ascii"),
        "nonce_b64": base64.b64encode(nonce).decode("ascii"),
        "ciphertext_b64": base64.b64encode(ciphertext).decode("ascii"),
        "plaintext_sha256": hashlib.sha256(payload).hexdigest(),
    }


def consume(envelope_path: Path, private_key_path: Path, expected_run_id: str, output: Path) -> dict:
    env = json.loads(envelope_path.read_text(encoding="utf-8"))
    private_raw = _b64d(private_key_path.read_text(encoding="ascii").strip())
    if len(private_raw) != 32:
        raise RuntimeError("input recipient private key invalid")
    plaintext = _decrypt_input(env, private_raw, expected_run_id)
    with tempfile.TemporaryDirectory(prefix="semiconductor-forward-") as td:
        root = Path(td)
        manifest = _safe_extract(plaintext, root)
        return_payload, receipt = _run_private_harness(root)
        return_envelope = _encrypt_return(return_payload, manifest, expected_run_id)
        output.write_text(json.dumps(return_envelope, sort_keys=True) + "\n", encoding="utf-8")
        return receipt


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--envelope", required=True)
    p.add_argument("--private-key", required=True)
    p.add_argument("--run-id", required=True)
    p.add_argument("--return-envelope", required=True)
    args = p.parse_args()
    receipt = consume(
        Path(args.envelope),
        Path(args.private_key),
        args.run_id,
        Path(args.return_envelope),
    )
    print("SEMICONDUCTOR_FORWARD_PUBLIC_RECEIPT=" + json.dumps(receipt, sort_keys=True))


if __name__ == "__main__":
    main()
